#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<EOSQL

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = '${POSTGRES_USER}'
    ) THEN
        CREATE ROLE "${POSTGRES_USER}"
            LOGIN
            PASSWORD '${POSTGRES_PASSWORD}';
    END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_USER}";

ALTER ROLE "${POSTGRES_USER}" SET search_path = public;

GRANT USAGE ON SCHEMA public TO "${POSTGRES_USER}";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO "${POSTGRES_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO "${POSTGRES_USER}";

EOSQL